### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by PLUCS2** [akerpelm/infinote#3]
- [x] Since you are not implementing the ability to Share Notes or Tags, you will only ever need to have one user in your state (the current user) 
- [x] The created should be a dateTime that (when rendered to the user) is converted to something like "a few seconds ago" or "yesterday" 
- [x] In your errors slice of state you will only have 1 login or signup key - it will most likely be a sessions key that points to errors from the users signup or login 

Let me know if you have any questions and nice work!

**Comment by akerpelm** [comment]
changes were made. Removed extraneous info, make all slices of state pertain to just one user, changed errors slice to have a key of session pointing to an array with the given error.
